### ISSUE TITLE
比赛数据集

### ISSUE THREAD

**Issue by asd46123** [LittleBoyHack/2018-NanJing-AI-Application-Competition#1]
你好，不知道还有没有比赛数据集可以分享吗？

**Comment by littlehacker26** [comment]
有的，可以邮箱发你

**Comment by asd46123** [comment]
太感谢你啦！！！我的邮箱是：532374119@qq.com

**Comment by wangbaiqi355920251** [comment]
你好，可以发一份数据集给我吗？感谢！！355920251@qq.com

**Comment by luckybaicai** [comment]
您好，不知道这么长时间了数据集还有吗？可以分享给我一份吗？给您添麻烦了！我邮箱是：2979128943@qq.com

**Comment by wangbaiqi355920251** [comment]
你上那个kaggle搜一下，那里边有




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LittleBoyHacker/2018-NanJing-AI-Application-Competition"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月16日(星期五) 下午3:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LittleBoyHacker/2018-NanJing-AI-Application-Competition] 比赛数据集 (#1)





 
***@***.***

**Comment by littlehacker26** [comment]
已发邮箱

**Comment by luckybaicai** [comment]
> 

谢谢，收到了已经！！！

**Comment by huangbaien** [comment]
您好，不知道这么长时间了数据集还有吗？可以分享给我一份吗？给您添麻烦了！我邮箱是：1649586303@qq.com

**Comment by littlehacker26** [comment]
> 您好，不知道这么长时间了数据集还有吗？可以分享给我一份吗？给您添麻烦了！我邮箱是：[1649586303@qq.com](mailto:1649586303@qq.com)

链接: https://pan.baidu.com/s/1xTZpFGVwNbsRe04ebJrAdQ   提取码: fbsb 

供你参考，希望能帮到你！
